# Generated by Django 4.1.4 on 2024-06-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='chapter_text_1',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='chapter_text_2',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='chapter_text_3',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='chapter_text_4',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='chapter_text_5',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='chapter_text_6',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
