# Generated by Django 4.1.4 on 2024-06-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_report_chapters_remove_report_regions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reporttype',
            old_name='prompt',
            new_name='chapter_prompt',
        ),
        migrations.AddField(
            model_name='reporttype',
            name='prompt_search',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='reporttype',
            name='prompt_vector',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
