# Generated by Django 4.1.4 on 2024-06-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_rename_prompt_reporttype_chapter_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='end_date',
            field=models.DateField(default='1111-11-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='start_date',
            field=models.DateField(default='1111-11-11'),
            preserve_default=False,
        ),
    ]
