# Generated by Django 4.1.4 on 2024-06-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_report_end_date_report_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='filters',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
