# Generated by Django 4.1.4 on 2024-06-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_report_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_text',
            field=models.TextField(),
        ),
    ]
