# Generated by Django 4.1.4 on 2024-06-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_chapter_chapter_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_analysis_parameters',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_comments',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_validation',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
