# Generated by Django 4.1.4 on 2024-06-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_chapter_chapter_analysis_parameters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='graphics',
        ),
        migrations.AddField(
            model_name='chapter',
            name='graphics',
            field=models.FileField(blank=True, null=True, upload_to='documents/graphics'),
        ),
    ]
