# Generated by Django 4.1.4 on 2024-06-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_chapter_table_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='plot_comments',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='table_comments',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
