# Generated by Django 4.1.4 on 2024-06-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_chapter_plot_comments_chapter_table_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='plot_code',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='plot_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
